server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - TokenRelay=

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:5050/realms/distributed-security
        registration:
          api-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: tisRFMRiEcKrYOEbyOEZOh1ObIk8YGcy
            authorization-grant-type: authorization_code
            scope: openid

management:
  tracing:
    sampling:
      probability: 1.0