spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 9090

management:
  tracing:
    sampling:
      probability: 1.0