services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - distributed-security-net
    restart: unless-stopped

  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 5050:8080
    environment:
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: 12345
    networks:
      - distributed-security-net
    command:
      - "start-dev"

  zipkin:
    container_name: zipkin_container
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    networks:
      - distributed-security-net

networks:
  distributed-security-net:
    driver: bridge

volumes:
  mysql: